[package]
name = "rustic_rover"
version = "1.2.0"
edition = "2021"

[dependencies]
iced = {version="0.12.0", features=["image"]}
tokio = {version = "1", features=["full"]}
hidapi = "2.6.0"
serialport = "4.2.0"