/**:
  x:
    plus: "Down_Key"
    minus: "Up_Key"
    rate: 100
  y:
    plus: "Right_Key"
    minus: "Left_Key"
    rate: 100
  rotation:
    plus: "Right_Stick_X"
    minus: "Right_Stick_X"
    rate: 100
  m1:
    plus: "Circle_Button"
    minus: "Cross_Button"
    rate: 100
  m2:
    plus: "R1_Button"
    minus: "L1_Button"
    rate: 100